const mongoose = require('mongoose');

const QAHistorySchema = new mongoose.Schema(
  {
    // bot to which the qa belongs to
    bot: { type: mongoose.Schema.Types.ObjectId, ref: 'ChatBot' },

    // query of the user/query generated by AI
    question: String,

    // answer to the query
    answer: String,

    // embeddings of the question to match the query embedding while finding best question match
    embedding: Buffer,

    // source metadata for the QA, used to retain or remove QAs for specific files
    source: { type: String, default: 'file' },
    sourceFileName: String,
    sourceFileHash: String,
  },
  { timestamps: true },
);

module.exports = mongoose.model('QAHistoryV2', QAHistorySchema);
